# Generated by Django 5.1.6 on 2025-07-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_notificationpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_attempts_remaining',
        ),
        migrations.RemoveField(
            model_name='user',
            name='must_change_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reactivation_task_id',
        ),
    ]
