# Generated by Django 5.1.6 on 2025-07-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_account_locked_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
