name: Checks

on:
  pull_request:
    branches: [main, develop]

permissions:
  id-token: write
  contents: read

env:
  ENV_FILE: ${{ secrets.TEST_ENV }}

jobs:
  test-lint:
    name: Test
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .env file
        run: |
          touch .env && printf "%s" "$ENV_FILE" > .env && cat .env

      - name: Build and run tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate && pytest -s"